### ISSUE TITLE
Make an APK downloadable for non technical users

### ISSUE THREAD

**Issue by davidbtc2009** [talkback-foss-team/talkback-foss#19]
I am a user who is good at helping with bug reports, etc but i dont understand the first bit about gradle, how to install it, where to install ot, how to build the source, etc. Please make the release downloadable from your github

**Comment by PatrykMis** [comment]
Will try to do it this week, but I'd prefer tu wait and rebase it into latest 12.2 upstream code which is not published to Github yet. They updated Liblouis to v3.20.0 which is big major change improving various things. Ping @Simplexatg on any of [original TalkBack repo's](https://github.com/google/talkback) pull request to do this - they have to know there is big interest on this.

**Comment by My1** [comment]
any updates to this?

**Comment by PatrykMis** [comment]
It's not ready for release yet. Back button in Preferences is not working correctly which is upstream bug of TalkBack's open source release from v12.1. Also there is light theme whitch is not adapting to device's theme or light/dark mode. Although theme is fixable in an easy way, the back button is more important issue I think.

Edit: theming fixed.

**Comment by PatrykMis** [comment]
Release has been published: https://github.com/talkback-foss-team/talkback-foss/releases/tag/v13.0.0.473912301-f01
