### ISSUE TITLE
migrate Groovy build system to fully Kotlin

### ISSUE THREAD

**Issue by Zanthed** [talkback-foss-team/talkback-foss#3]

**Comment by PatrykMis** [comment]
Ok, work begun [on branch build_kotlin](https://github.com/talkback-foss-team/talkback-foss/tree/build_kotlin).

**Comment by PatrykMis** [comment]
Wondering…
Daniel Micay says:

> @Patryk_Mis The advantage of the Kotlin DSL is having a nicer language with static typing so you get help with avoiding errors in the build system. Not worth migrating TalkBack since it will make upstream releases much harder to incorporate in the future. Also an issue for making changes.

(source: https://twitter.com/DanielMicay/status/1475253074050662405)

**Comment by PatrykMis** [comment]
https://github.com/talkback-foss-team/talkback-foss/pull/30 merged, but with that low interest from the community we should drop this change on next upstream rebase.b
