### ISSUE TITLE
Gesture to accept An incoming phone call do not work if Termux or Termux-x11 window is active

### ISSUE THREAD

**Issue by JanuszChmiel** [talkback-foss-team/talkback-foss#79]
Dear elite Talkback FOS developers,
I would like to express my deepest possible appreciation to you. Because you have extending and you are making Talkback more user friendly. I think, that your knowledge of Talkback source code is very deep and good. So I Am sure, that somebody elite among us could help me with The following problem.
If I install Termux application from Google Play store. If I run it on Android 11 phone, if somebody call Me by using Phone call, I AM helpless to accept this incoming phone call.
Build in special Talkback gesture to accept or reject An incoming phone call do not work.
So if I put my two finger to The touch display. And If I swipe with those two finger tips by swiping from down to up I can not accept incoming phone call.
Do you think, thatsomebody of us could try to find The cause of such strange behaviour?
I Am using An official Phone system app from my phone manufacturer. Sure, this build in Talkback gesture for accepting incoming phone call also work for official Google Phone application.
I Am using 
TECNO Mobile SPARK 8T mobile phone with Android 11 version.
The same problem persists for Termux-x11 because its code is also partially based on Termux terminal emulator.
Any debate or cause of this issue will be very welcomed.
Thank you for your help and for your time.
With The deepest possible appreciation and with The warmest regards.
Janusz Chmiel

**Comment by PatrykMis** [comment]
I don't have Android <13 device to test it, but as far as I know you can answer the phone call by double tapping with two fingers and it works in all situations.

**Comment by JanuszChmiel** [comment]
Dear MR Mis,
Thank you very much for your very fst answer.
I Am using Android 11 phone. Is it so easy that if floating window with incoming phone call button appear that user can double tap with two fingers somewhere on The screen? Or user must double tap with two fingers only to The button for accepting incoming call? I will try that.

**Comment by JanuszChmiel** [comment]
Unfortunately it is not simply possible to accept incoming call by double tapping with two fingers if Termux window is active.
But thank you for your patience and thank you for your good will to help Me.

**Comment by JanuszChmiel** [comment]
I have found out very interesting fact. Reliable way to answer incoming phone call is. If The phone screen have been turned off. And somebody is calling.
In this case, The phone wake up and Talkback allow user to answer phone call by using two fingers gesture swiping from down to up.
The problem always start, if Thephone screen is turned on and focus resides in other active window.
In this case, my favourite gesture do not work.
I will compare this behaviour with official Android accessibility solution.
BUt I Am afraid, that if The phone app display special floating window, gesture swiping from down to up with The two fingers will never work.
